noto-nerd-install downloading to ~/Downloads/Fonts/Nerd

diff --git a/noto-nerd-install b/noto-nerd-install
--- a/noto-nerd-install
+++ b/noto-nerd-install
@@ -1,32 +1,31 @@
-#!/bin/bash
-# Borrowed from https://github.com/officialrajdeepsingh/nerd-fonts-installer
-#
+#!/usr/bin/env bash
+
 font_name="Noto"
+download_dir="$HOME/Downloads/Fonts/Nerd"
+mkdir -p "$download_dir"
 
 echo "Starting download $font_name nerd font"
 
-if [ "$(command -v curl)" ]; then
-    echo "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
-    curl -OL "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
-    echo "creating fonts folder: ${HOME}/.fonts"
-    mkdir -p  "$HOME/.fonts"
-    echo "unzip the $font_name.zip"
-    unzip "$font_name.zip" -d "$HOME/.fonts/$font_name/"
-    #fc-cache -fv
-    echo "done!"
+cd "$download_dir"
 
-elif [ "$(command -v wget)" ]; then
-    echo "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
-    wget "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
-    echo "creating fonts folder: ${HOME}/.fonts"
-    mkdir -p  "$HOME/.fonts"
-    echo "unzip the $font_name.zip"
-    unzip "$font_name.zip" -d "$HOME/.fonts/$font_name/"
-    #fc-cache -fv
-    echo "done!"
+if ! test -e "$font_name.zip"; then
+    if [ "$(command -v curl)" ]; then
+        echo "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
+        curl -OL "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
+    elif [ "$(command -v wget)" ]; then
+        echo "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
+        wget "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
+    else
 
-else
-    
-    echo "We cannot find the curl and wget command. First, install the curl and wget command, one of them."
+        echo "We cannot find the curl and wget command. First, install the curl and wget command, one of them."
+        exit 1
 
+    fi
 fi
+
+echo "creating fonts folder: ${HOME}/.fonts"
+mkdir -p  "$HOME/.fonts"
+echo "unzip the $font_name.zip"
+unzip "$font_name.zip" -d "$HOME/.fonts/$font_name/"
+fc-cache -fv
+echo "done!"
